### 로그인
POST http://localhost:8081/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "id": "test",
  "pwd": "test"

}

### 로그아웃
POST http://localhost:8081/auth/logout
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTkzNzMyNzcsInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5OTMzMDA3NywiYXV0aCI6IlJPTEVfVVNFUiIsIm1lbWJlcklkIjoidGVzdCJ9.iQeZb7Cha8DLL3u6li59rKwbNUfVwajT7e_6A-vgQoBUfHnyvnaij1cdkwO92Z_XXFOWP_nfcpZpudSIw8TgAA


### 토큰 재발급
POST http://localhost:8081/auth/reissue
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
