### 로그인
POST http://localhost:8081/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "id": "admin",
  "pwd": "admin"

}

### 로그아웃
POST http://localhost:8081/auth/logout
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTg5MDI2OTUsInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5ODkwMjY1MiwiYXV0aCI6IlJPTEVfQURNSU4iLCJtZW1iZXJJZCI6ImFkbWluIn0.WSB2J2jm9hDsJuH-41m2kdQQspGkNkldGkd1S5vgUZdhLr4kYA8LB1tL0ZMpjS_NgfyuwN-kVmbNj3vYCoGh5A


### 토큰 재발급
POST http://localhost:8081/auth/reissue
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
