### 회원가입 / 회원 등록
POST http://localhost:8081/api/v1/member/join
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTg5NzgyNzQsInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5ODk3ODIzMSwiYXV0aCI6IlJPTEVfQURNSU4iLCJtZW1iZXJJZCI6ImFkbWluIn0.q5_KEiLiZaU-mbZnvaHuYr67e-T4ew8XIGpbRZuegiMbc7dQjLtXe6vsrANLnMerxdgVf1GO3oOrLCNOLAnvUA

{
  "memberId": "admin",
  "memberPwd": "admin",
  "memberName": "admin",
  "zipCode": "1212",
  "address": "대전",
  "addressDetail": "예시",
  "profile": "default.jpg"
}

### 전체직원조회
GET http://localhost:8081/api/v1/member/members
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTkyODQ2NjksInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5OTI0MTQ2OSwiYXV0aCI6IlJPTEVfQURNSU4iLCJtZW1iZXJJZCI6ImFkbWluIn0.-9JxtoYZNE9d55Qif0tD57SLs-8v54j2NNJSn4lHrK8qTcB6dp9yKNT44FxzYKnm8JOkd-cVA2upx6jqkWXbwQ


### 한명조회
GET http://localhost:8081/api/v1/member/admin
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTkyODQ2NjksInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5OTI0MTQ2OSwiYXV0aCI6IlJPTEVfQURNSU4iLCJtZW1iZXJJZCI6ImFkbWluIn0.-9JxtoYZNE9d55Qif0tD57SLs-8v54j2NNJSn4lHrK8qTcB6dp9yKNT44FxzYKnm8JOkd-cVA2upx6jqkWXbwQ


### 회원정보 수정
PATCH http://localhost:8081/api/v1/member/admin
Content-Type: application/json
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2OTg3ODY2NTgsInN1YiI6ImFjY2Vzcy10b2tlbiIsImlhdCI6MTY5ODc0MzQ1OCwiYXV0aCI6IlJPTEVfQURNSU4iLCJtZW1iZXJJZCI6ImFkbWluIn0.CH03-AWJN0WZzb6gQj7-2O_s4szTmdL3NsWnRt-_JVdUzu87bCkfApp1E77UowPstJF9VJDFkD2LcMwMDUg_ag

{
  "memberPwd": "admin",
  "memberName": "admin",
  "zipCode": "3333",
  "address": "대전",
  "addressDetail": "예시",
  "profile": "default.jpg"
}

### 정의



